# Generated by Django 2.2.5 on 2019-09-22 22:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255, null=True)),
                ('argument', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
            ],
            options={
                'unique_together': {('group', 'argument', 'value')},
            },
        ),
        migrations.CreateModel(
            name='FileBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('path', models.CharField(max_length=512, null=True)),
                ('languages', models.ManyToManyField(editable=False, related_name='simulators', to='manager.Language')),
            ],
        ),
        migrations.CreateModel(
            name='TestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teros_project', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('result', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatorArgument',
            fields=[
                ('argumentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.ArgumentBase')),
            ],
            bases=('manager.argumentbase',),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('filebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.FileBase')),
            ],
            bases=('manager.filebase',),
        ),
        migrations.CreateModel(
            name='SuiteArgument',
            fields=[
                ('argumentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.ArgumentBase')),
            ],
            bases=('manager.argumentbase',),
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('filebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.FileBase')),
            ],
            bases=('manager.filebase',),
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('simulators', models.ManyToManyField(editable=False, related_name='suites', to='manager.Simulator')),
            ],
        ),
        migrations.CreateModel(
            name='EdalizeTest',
            fields=[
                ('testbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.TestBase')),
                ('working_dir', models.CharField(max_length=512)),
                ('top_level', models.CharField(max_length=128)),
                ('edalize_args', models.ManyToManyField(to='manager.SuiteArgument')),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Simulator')),
                ('simulator_args', models.ManyToManyField(to='manager.SimulatorArgument')),
                ('sources', models.ManyToManyField(to='manager.SourceFile')),
            ],
            bases=('manager.testbase',),
        ),
        migrations.CreateModel(
            name='CocoTest',
            fields=[
                ('testbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.TestBase')),
                ('working_dir', models.CharField(max_length=512)),
                ('top_level', models.CharField(max_length=128)),
                ('modules', models.ManyToManyField(to='manager.TestFile')),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Simulator')),
                ('simulator_args', models.ManyToManyField(to='manager.SimulatorArgument')),
                ('sources', models.ManyToManyField(to='manager.SourceFile')),
            ],
            bases=('manager.testbase',),
        ),
    ]
