# Generated by Django 2.2.4 on 2019-09-14 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('languages', models.ManyToManyField(editable=False, related_name='simulators', to='manager.Language')),
            ],
        ),
        migrations.CreateModel(
            name='TestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('simulators', models.ManyToManyField(editable=False, related_name='suites', to='manager.Simulator')),
            ],
        ),
        migrations.CreateModel(
            name='CocoTest',
            fields=[
                ('testbase_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='manager.TestBase')),
                ('name', models.CharField(max_length=255)),
                ('top_level', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('_tests', models.CharField(db_column='tests', max_length=255)),
                ('_files', models.CharField(db_column='files', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Language')),
                (
                'simulator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Simulator')),
            ],
            bases=('manager.testbase',),
        ),
        migrations.CreateModel(
            name='CocoOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options',
                                           to='manager.CocoTest')),
            ],
        ),
    ]
